canonifyurls = true
baseURL = 'https://www.kaluosifa.com'
languageCode = 'zh-cn'
title = "Kaluosifa's Blog"
paginate = 5
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true

[minify]
disableXML = true

[taxonomies]
  category = 'categories'
  tag = 'tags'

[[menu.main]]
name = 'ä¸»é¡µ'
url = '/'
weight = 10
[[menu.main]]
name = "å½’æ¡£"
url = "/archives/"
weight = 20
[[menu.main]]
name = "æœç´¢"
url = "/Search/"
weight = 30
[[menu.main]]
name = "åˆ†ç±»"
url = "/categories/"
weight = 40
[[menu.main]]
name = "æ ‡ç­¾"
url = "/tags/"
weight = 50

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "è¿™æ˜¯ä¸€ä¸ªç”¨Hugoæ­å»ºçš„ä¸ªäººåšå®¢"
author = "kaluosifa"
defaultTheme = "auto"
ShowShareButtons = false
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true

  [params.homeInfoParams]
  Title = "Hi there ğŸ‘‹"
  Content = "æ¬¢è¿æ¥åˆ°å¡æ´›æ–¯æ³•çš„åšå®¢"

  [[params.socialIcons]]
  name = "github"
  url = "https://www.github.com/kaluosifa/"

  [[params.socialIcons]]
  name = "Rss"
  url = "index.xml"

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false